// Sample property listings data
const listings = [
  {
    id: 1,
    address: '123 Main St, Springfield',
    price: 450000,
    property_type: 'House',
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1800,
    lot_size_sqft: 5000,
    year_built: 1995,
    parking: 2,
    hoa_fees: 0,
    property_taxes: 4800,
    school_rating: 8,
    walk_score: 70,
    photos: ['main1.jpg'],
    features: ['Fireplace', 'Backyard', 'Central AC'],
  },
  {
    id: 2,
    address: '456 Oak Ave, Springfield',
    price: 470000,
    property_type: 'House',
    bedrooms: 4,
    bathrooms: 2.5,
    area_sqft: 2000,
    lot_size_sqft: 5200,
    year_built: 2000,
    parking: 2,
    hoa_fees: 0,
    property_taxes: 5100,
    school_rating: 9,
    walk_score: 75,
    photos: ['oak1.jpg'],
    features: ['Pool', 'Backyard', 'Central AC'],
  },
  {
    id: 3,
    address: '789 Pine Rd, Springfield',
    price: 430000,
    property_type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1600,
    lot_size_sqft: 2000,
    year_built: 2010,
    parking: 1,
    hoa_fees: 150,
    property_taxes: 4200,
    school_rating: 7,
    walk_score: 68,
    photos: ['pine1.jpg'],
    features: ['Balcony', 'Central AC'],
  },
  {
    id: 4,
    address: '101 Maple Dr, Springfield',
    price: 499000,
    property_type: 'Condo',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1400,
    lot_size_sqft: 1000,
    year_built: 2015,
    parking: 1,
    hoa_fees: 200,
    property_taxes: 3900,
    school_rating: 8,
    walk_score: 80,
    photos: ['maple1.jpg'],
    features: ['Gym', 'Balcony', 'Central AC'],
  },
];

export default listings;
